Repository letta-ai/letta, pull requests merged in 2023-12, with the labels that each got.

#555 Update autogen.md to include Azure config example + patch for `pyautogen>=0.2.0`
  docs/autogen.md
  memgpt/autogen/examples/agent_autoreply.py
  memgpt/autogen/examples/agent_docs.py
  memgpt/autogen/examples/agent_groupchat.py
  memgpt/autogen/memgpt_agent.py
  memgpt/openai_tools.py
Labels: autogen, azure

#594 Patch azure embeddings + handle azure deployments properly
  docs/endpoints.md
  memgpt/cli/cli_config.py
  memgpt/embeddings.py
  poetry.lock
  pyproject.toml
Labels: azure

#603 AutoGen misc fixes
  memgpt/agent.py
  memgpt/autogen/interface.py
  memgpt/autogen/memgpt_agent.py
  memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
  memgpt/system.py
Labels: autogen

#611 added `memgpt server` command
  memgpt/cli/cli.py
  memgpt/main.py
  memgpt/server/constants.py
  memgpt/server/rest_api/interface.py
  memgpt/server/rest_api/server.py
  memgpt/server/server.py
  memgpt/server/utils.py
  memgpt/server/ws_api/example_client.py
  memgpt/server/ws_api/server.py
  tests/test_websocket_server.py
Labels: API

#585 updated local APIs to return usage info
  memgpt/local_llm/chat_completion_proxy.py
  memgpt/local_llm/koboldcpp/api.py
  memgpt/local_llm/llamacpp/api.py
  memgpt/local_llm/lmstudio/api.py
  memgpt/local_llm/ollama/api.py
  memgpt/local_llm/vllm/api.py
  memgpt/local_llm/webui/api.py
  memgpt/local_llm/webui/legacy_api.py
Labels: local-llm, priority

#576 Add safeguard on tokens returned by functions
  docs/functions.md
  memgpt/agent.py
  memgpt/constants.py
  memgpt/functions/function_sets/base.py
  memgpt/functions/functions.py
  memgpt/utils.py
Labels: priority

#618 allow passing custom host to rest server
  memgpt/cli/cli.py
Labels: API

#629 Patch bug with loading of old agents
  memgpt/openai_backcompat/openai_object.py
  memgpt/persistence_manager.py
  memgpt/utils.py
Labels: priority

#631 feat: Add common + custom settings files for completion endpoints
  memgpt/local_llm/koboldcpp/api.py
  memgpt/local_llm/llamacpp/api.py
  memgpt/local_llm/lmstudio/api.py
  memgpt/local_llm/ollama/api.py
  memgpt/local_llm/settings/__init__.py
  memgpt/local_llm/settings/deterministic_mirostat.py
  memgpt/local_llm/settings/settings.py
  memgpt/local_llm/settings/simple.py
  memgpt/local_llm/vllm/api.py
  memgpt/local_llm/webui/api.py
  memgpt/local_llm/webui/legacy_api.py
Labels: local-llm, priority

#647 feat: Update REST API
  memgpt/server/rest_api/agents/command.py
  memgpt/server/rest_api/agents/config.py
  memgpt/server/rest_api/agents/index.py
  memgpt/server/rest_api/agents/memory.py
  memgpt/server/rest_api/agents/message.py
  memgpt/server/rest_api/config/index.py
  memgpt/server/utils.py
Labels: API, ChatUI

#641 feat: Add `memgpt quickstart` command
  configs/memgpt_hosted.json
  configs/openai.json
  memgpt/cli/cli.py
  memgpt/local_llm/chat_completion_proxy.py
  memgpt/local_llm/vllm/api.py
  memgpt/main.py
Labels: priority

#656 feat: Add new wrapper defaults
  configs/memgpt_hosted.json
  memgpt/agent.py
  memgpt/local_llm/chat_completion_proxy.py
  memgpt/local_llm/constants.py
  memgpt/local_llm/llm_chat_completion_wrappers/chatml.py
  memgpt/local_llm/settings/simple.py
  memgpt/local_llm/utils.py
  memgpt/memory.py
  memgpt/openai_tools.py
  memgpt/utils.py
Labels: priority

#630 feat: pull model list for openai-compatible endpoints
  memgpt/cli/cli_config.py
  memgpt/openai_tools.py
Labels: priority

#621 feat: added basic heartbeat override heuristics
  memgpt/constants.py
  memgpt/local_llm/chat_completion_proxy.py
  memgpt/local_llm/function_parser.py
  memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
  memgpt/local_llm/llm_chat_completion_wrappers/chatml.py
  tests/test_function_parser.py
Labels: priority

#713 feat: Add MemGPT "Python Client"
  README.md
  docs/python_client.md
  memgpt/__init__.py
  memgpt/cli/cli.py
  memgpt/client/__init__.py
  memgpt/client/client.py
  memgpt/config.py
  memgpt/server/rest_api/interface.py
  memgpt/server/rest_api/server.py
  memgpt/server/server.py
  tests/test_client.py
  tests/test_websocket_interface.py
  tests/utils.py
Labels: priority, API
