Repository letta-ai/letta, pull requests merged in 2024-01, with the labels that each got.

#708 refactor!: Refactoring storage connectors to support multi-user DB storage for recall memory + metadata
  .github/workflows/tests.yml
  memgpt/agent.py
  memgpt/autogen/memgpt_agent.py
  memgpt/cli/cli.py
  memgpt/cli/cli_config.py
  memgpt/cli/cli_load.py
  memgpt/config.py
  memgpt/connectors/chroma.py
  memgpt/connectors/db.py
  memgpt/connectors/lancedb.py
  memgpt/connectors/local.py
  memgpt/connectors/storage.py
  memgpt/data_types.py
  memgpt/embeddings.py
  memgpt/main.py
  memgpt/memory.py
  memgpt/persistence_manager.py
  memgpt/utils.py
  poetry.lock
  pyproject.toml
  tests/test_base_functions.py
  tests/test_cli.py
  tests/test_client.py
  tests/test_load_archival.py
  tests/test_storage.py
  tests/utils.py
Labels: priority

#783 fix: Update message schema / data type to match OAI tools style
  memgpt/agent.py
  memgpt/connectors/db.py
  memgpt/data_types.py
  memgpt/persistence_manager.py
Labels: priority

#784 feat: add_function and remove_function commands
  memgpt/agent.py
  memgpt/functions/functions.py
  memgpt/main.py
  tests/test_agent_function_update.py
Labels: priority

#790 feat: Feature/global logging
  memgpt/cli/cli.py
  memgpt/cli/cli_config.py
  memgpt/config.py
  memgpt/constants.py
  memgpt/log.py
  memgpt/main.py
  tests/test_log.py
Labels: priority

#796 feat: Added grammar generator for function calling.
  memgpt/agent.py
  memgpt/local_llm/chat_completion_proxy.py
  memgpt/local_llm/grammars/__init__.py
  memgpt/local_llm/grammars/gbnf_grammar_generator.py
  memgpt/local_llm/koboldcpp/api.py
  memgpt/local_llm/llamacpp/api.py
  memgpt/local_llm/utils.py
  memgpt/local_llm/webui/api.py
  memgpt/local_llm/webui/legacy_api.py
  memgpt/openai_tools.py
Labels: priority

#851 feat: Get in-context `Message.id` values from server
  memgpt/memory.py
  memgpt/server/server.py
  tests/test_server.py
Labels: API

#816 feat: Benchmark Command: `memgpt benchmark`
  memgpt/agent.py
  memgpt/autogen/memgpt_agent.py
  memgpt/benchmark/benchmark.py
  memgpt/benchmark/constants.py
  memgpt/client/client.py
  memgpt/config.py
  memgpt/main.py
  memgpt/server/server.py
  tests/test_load_archival.py
  tests/test_migrate.py
Labels: priority

#882 feat: add agent rename and agent delete to server + REST
  memgpt/server/rest_api/agents/config.py
  memgpt/server/server.py
Labels: API, ChatUI

#905 refactor: refactor MemGPT + AutoGen integration to work with MemGPT `0.2.12`+ (DB release)
  docs/autogen.md
  docs/python_client.md
  memgpt/agent.py
  memgpt/autogen/examples/agent_autoreply.py
  memgpt/autogen/examples/agent_docs.py
  memgpt/autogen/examples/agent_groupchat.py
  memgpt/autogen/examples/memgpt_coder_autogen.ipynb
  memgpt/autogen/interface.py
  memgpt/autogen/memgpt_agent.py
  memgpt/cli/cli.py
  memgpt/cli/cli_load.py
  memgpt/main.py
  memgpt/presets/presets.py
  tests/test_load_archival.py
Labels: autogen

#899 feat: Chatui agent dropdown fields
  chatui/README.md
  chatui/src/app/libs/humans/human.ts
  chatui/src/app/libs/humans/use-humans.query.ts
  chatui/src/app/libs/models/model.ts
  chatui/src/app/libs/models/use-models.query.ts
  chatui/src/app/libs/personas/persona.ts
  chatui/src/app/libs/personas/use-personas.query.ts
  chatui/src/app/modules/home/create-agent-dialog.tsx
  memgpt/server/rest_api/humans/__init__.py
  memgpt/server/rest_api/humans/index.py
  memgpt/server/rest_api/models/__init__.py
  memgpt/server/rest_api/models/index.py
  memgpt/server/rest_api/personas/__init__.py
  memgpt/server/rest_api/personas/index.py
  memgpt/server/rest_api/server.py
Labels: ChatUI
